package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/frederik-jatzkowski/havel/pkg/hvil/pass/parser"
)

func NewHvilGrammarCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "grammar",
		Short: "Returns an autogenerated hvil grammar",
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Println(parser.String())

			return nil
		},
	}

	return cmd
}
